// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] 
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8uQ7eGMSstxhaI7rhhZB8AtRizHbh1As',
    appId: '1:91325074390:web:db3df086e8dd477c073277',
    messagingSenderId: '91325074390',
    projectId: 'hayateli-c6101',
    authDomain: 'hayateli-c6101.firebaseapp.com',
    storageBucket: 'hayateli-c6101.firebasestorage.app',
    measurementId: 'G-2151LF8R82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzf_HIpn0Km2SCQNDbVrowIvD3LOlwQM',
    appId: '1:91325074390:android:c71a9522d671d8e2073277',
    messagingSenderId: '91325074390',
    projectId: 'hayateli-c6101',
    storageBucket: 'hayateli-c6101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzKl0jcP5aDc26E_CZLO883jJ_bqt6me8',
    appId: '1:91325074390:ios:50f5e3f2a6f980db073277',
    messagingSenderId: '91325074390',
    projectId: 'hayateli-c6101',
    storageBucket: 'hayateli-c6101.firebasestorage.app',
    iosBundleId: 'com.example.hayatEliMobilUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzKl0jcP5aDc26E_CZLO883jJ_bqt6me8',
    appId: '1:91325074390:ios:50f5e3f2a6f980db073277',
    messagingSenderId: '91325074390',
    projectId: 'hayateli-c6101',
    storageBucket: 'hayateli-c6101.firebasestorage.app',
    iosBundleId: 'com.example.hayatEliMobilUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8uQ7eGMSstxhaI7rhhZB8AtRizHbh1As',
    appId: '1:91325074390:web:364fdf6ff4e8ae8b073277',
    messagingSenderId: '91325074390',
    projectId: 'hayateli-c6101',
    authDomain: 'hayateli-c6101.firebaseapp.com',
    storageBucket: 'hayateli-c6101.firebasestorage.app',
    measurementId: 'G-PJE9WE2XWD',
  );
}
